
import { Building, Resources, Research, Ship, Defense, Officer } from './types';

export const INITIAL_RESOURCES: Resources = {
  risitasium: 500,
  stickers: 300,
  sel: 0,
  karma: 0,
  karmaMax: 0,
  redpills: 50, // Un peu de monnaie premium offerte au départ
};

export const OFFICER_DB: Officer[] = [
  {
    id: 'off_celestin',
    name: 'Ingénieur Célestin',
    description: 'Optimise la production d\'énergie en pédalant plus vite.',
    cost: 100,
    bonus: '+10% Production Énergie',
    active: false,
    image: 'https://images.unsplash.com/photo-1518770660439-4636190af475?q=80&w=500&auto=format&fit=crop'
  },
  {
    id: 'off_modo',
    name: 'Modérateur Corrompu',
    description: 'Ferme les yeux sur vos activités illicites.',
    cost: 250,
    bonus: '+2 Slots de Flotte',
    active: false,
    image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=500&auto=format&fit=crop'
  },
  {
    id: 'off_stalker',
    name: 'Commandant Stalker',
    description: 'Améliore la vitesse des vaisseaux lors des raids.',
    cost: 500,
    bonus: '+10% Vitesse Flotte',
    active: false,
    image: 'https://images.unsplash.com/photo-1614726365723-49faaa559036?q=80&w=500&auto=format&fit=crop'
  }
];

export const DEFENSE_DB: Defense[] = [
  {
    id: 'lanceur_pls',
    name: 'Lanceur de PLS',
    description: 'Tourelle de base. Met l\'ennemi en Position Latérale de Sécurité.',
    count: 0,
    baseCost: { risitasium: 2000, stickers: 0, sel: 0 },
    costFactor: 1,
    basePoints: 2,
    stats: { attack: 80, defense: 20, hull: 200, capacity: 0 },
    reqs: { 'chantier_spatial': 1 },
    image: 'https://images.unsplash.com/photo-1589987820063-8e100259163e?q=80&w=500&auto=format&fit=crop'
  },
  {
    id: 'laser_gneugneu',
    name: 'Laser "Gneu Gneu"',
    description: 'Émet une fréquence agaçante qui perturbe les boucliers.',
    count: 0,
    baseCost: { risitasium: 1500, stickers: 500, sel: 0 },
    costFactor: 1,
    basePoints: 4,
    stats: { attack: 100, defense: 25, hull: 200, capacity: 0 },
    reqs: { 'chantier_spatial': 2, 'tech_laser': 3 },
    image: 'https://images.unsplash.com/photo-1491591462767-3b91b2a19487?q=80&w=500&auto=format&fit=crop'
  },
  {
    id: 'canon_pave',
    name: 'Canon à Pavé César',
    description: 'Projette des blocs de texte illisibles à haute vélocité.',
    count: 0,
    baseCost: { risitasium: 6000, stickers: 2000, sel: 0 },
    costFactor: 1,
    basePoints: 10,
    stats: { attack: 250, defense: 100, hull: 800, capacity: 0 },
    reqs: { 'chantier_spatial': 6, 'tech_energie': 6, 'tech_armure': 3 },
    image: 'https://images.unsplash.com/photo-1590422964522-83569727402c?q=80&w=500&auto=format&fit=crop'
  },
  {
    id: 'bouclier_safe_space',
    name: 'Dôme Safe Space',
    description: 'Protège la colonie des agressions visuelles.',
    count: 0,
    baseCost: { risitasium: 10000, stickers: 10000, sel: 0 },
    costFactor: 1,
    basePoints: 25,
    stats: { attack: 1, defense: 2000, hull: 2000, capacity: 0 },
    reqs: { 'chantier_spatial': 1, 'tech_bouclier': 2 },
    image: 'https://images.unsplash.com/photo-1468273513361-9c6a17b87827?q=80&w=500&auto=format&fit=crop'
  },
  {
    id: 'canon_plasma',
    name: 'Projecteur de Malaise',
    description: 'L\'arme ultime. Crée un malaise si intense que les vaisseaux explosent.',
    count: 0,
    baseCost: { risitasium: 50000, stickers: 50000, sel: 30000 },
    costFactor: 1,
    basePoints: 150,
    stats: { attack: 3000, defense: 3000, hull: 10000, capacity: 0 },
    reqs: { 'chantier_spatial': 8, 'tech_plasma': 7 },
    image: 'https://images.unsplash.com/photo-1628126235206-5260b9ea6441?q=80&w=500&auto=format&fit=crop'
  }
];

export const BUILDING_DB: Building[] = [
  {
    id: 'mine_risitasium',
    name: 'Mine de Risitium',
    description: 'Extraction du minerai brut.',
    longDescription: 'Le Risitium est un métal extrêmement dense trouvé dans les profondeurs de la croûte terrestre des Topics. C\'est l\'élément fondateur de toute civilisation khey. Cette mine creuse inlassablement le sol pour remonter ce précieux matériau.',
    level: 0,
    baseCost: { risitasium: 60, stickers: 15, sel: 0 },
    costFactor: 1.5,
    basePoints: 1,
    production: { type: 'risitasium', base: 30, factor: 1.1 },
    energyType: 'consumer',
    consumption: { type: 'karma', base: 10, factor: 1.1 },
    image: 'https://images.unsplash.com/photo-1516937941344-00b4ec0c4663?q=80&w=500&auto=format&fit=crop',
  },
  {
    id: 'extracteur_stickers',
    name: 'Extracteur de Stickers',
    description: 'Cristallisation de données mémétiques.',
    longDescription: 'Les Stickers ne sont pas de simples images, ce sont des cristaux de données pures. L\'extracteur filtre le bruit ambiant du réseau pour cristalliser ces mèmes en matière utilisable.',
    level: 0,
    baseCost: { risitasium: 48, stickers: 24, sel: 0 },
    costFactor: 1.6,
    basePoints: 1,
    production: { type: 'stickers', base: 20, factor: 1.1 },
    energyType: 'consumer',
    consumption: { type: 'karma', base: 10, factor: 1.1 },
    image: 'https://images.unsplash.com/photo-1620712943543-bcc4688e7485?q=80&w=500&auto=format&fit=crop',
  },
  {
    id: 'raffineur_sel',
    name: 'Raffineur de Sel',
    description: 'Synthèse d\'isotopes lourds toxiques.',
    longDescription: 'Le Sel est un isotope lourd récolté dans l\'atmosphère toxique des sous-forums. Il sert de carburant haute performance pour les moteurs hyperespace et de réactif pour les recherches nucléaires.',
    level: 0,
    baseCost: { risitasium: 225, stickers: 75, sel: 0 },
    costFactor: 1.5,
    basePoints: 3,
    production: { type: 'sel', base: 10, factor: 1.1 },
    energyType: 'consumer',
    consumption: { type: 'karma', base: 20, factor: 1.1 },
    image: 'https://images.unsplash.com/photo-1518337231011-7b24300e84b6?q=80&w=500&auto=format&fit=crop',
  },
  {
    id: 'centrale_solaire',
    name: 'Centrale Solaire',
    description: 'Conversion photonique basique.',
    longDescription: 'Des panneaux photovoltaïques géants qui convertissent la lumière de l\'étoile locale en Karma positif. C\'est la source d\'énergie la plus basique et la plus fiable.',
    level: 0,
    baseCost: { risitasium: 75, stickers: 30, sel: 0 },
    costFactor: 1.5,
    basePoints: 2,
    production: { type: 'karma', base: 20, factor: 1.1 },
    energyType: 'producer',
    image: 'https://images.unsplash.com/photo-1509391366360-2e959784a276?q=80&w=500&auto=format&fit=crop',
  },
  {
    id: 'centrale_fusion',
    name: 'Réacteur à Fusion',
    description: 'Générateur haute énergie au Sel.',
    longDescription: 'En fusionnant des atomes de Sel sous haute pression, cette centrale génère une quantité phénoménale de Karma. Solution ultime pour l\'industrie lourde.',
    level: 0,
    baseCost: { risitasium: 900, stickers: 360, sel: 180 },
    costFactor: 1.8,
    basePoints: 15,
    production: { type: 'karma', base: 50, factor: 1.1 },
    energyType: 'producer',
    consumption: { type: 'sel', base: 5, factor: 1.1 },
    image: 'https://images.unsplash.com/photo-1478760329108-5c3ed9d495a0?q=80&w=500&auto=format&fit=crop',
  },
  {
    id: 'usine_golems',
    name: 'Usine de Golems',
    description: 'Chaîne de montage d\'ouvriers.',
    longDescription: 'Une chaîne de montage automatisée qui produit des ouvriers incatigables. Chaque niveau optimise la logistique et réduit drastiquement les temps de construction.',
    level: 0,
    baseCost: { risitasium: 400, stickers: 120, sel: 200 },
    costFactor: 2,
    basePoints: 10,
    energyType: 'consumer',
    consumption: { type: 'karma', base: 10, factor: 1.1 },
    image: 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?q=80&w=500&auto=format&fit=crop',
  },
  {
    id: 'laboratoire_recherche',
    name: 'Labo de Recherche',
    description: 'Centre de développement technologique.',
    longDescription: 'Le centre névralgique de l\'intelligence de votre empire. Ici, les savants étudient les mystères du Risitium et du Sel pour développer de nouveaux moteurs.',
    level: 0,
    baseCost: { risitasium: 200, stickers: 400, sel: 200 },
    costFactor: 2,
    basePoints: 10,
    energyType: 'consumer',
    consumption: { type: 'karma', base: 10, factor: 1.1 },
    image: 'https://images.unsplash.com/photo-1532094349884-543bc11b234d?q=80&w=500&auto=format&fit=crop',
  },
  {
    id: 'chantier_spatial',
    name: 'Chantier Spatial',
    description: 'Dock d\'assemblage de flotte.',
    longDescription: 'Un immense dock orbital capable d\'assembler des coques en alliage de Risitium. Nécessaire pour construire aussi bien des transporteurs civils que des croiseurs de bataille.',
    level: 0,
    baseCost: { risitasium: 400, stickers: 200, sel: 100 },
    costFactor: 2,
    basePoints: 10,
    energyType: 'consumer',
    consumption: { type: 'karma', base: 0, factor: 1 },
    reqs: { 'usine_golems': 2 },
    image: 'https://images.unsplash.com/photo-1614728853970-309140b774cf?q=80&w=500&auto=format&fit=crop',
  }
];

export const RESEARCH_DB: Research[] = [
  {
    id: 'tech_energie',
    name: 'Théorie du Karma',
    description: 'Compréhension des flux énergétiques.',
    level: 0,
    baseCost: { risitasium: 0, stickers: 800, sel: 400 },
    costFactor: 2,
    basePoints: 5,
    reqs: { 'laboratoire_recherche': 1 },
    image: 'https://images.unsplash.com/photo-1462331940025-496dfbfc7564?q=80&w=500&auto=format&fit=crop',
  },
  {
    id: 'tech_laser',
    name: 'Rayon DDB',
    description: 'Concentration de signalements à haute intensité.',
    level: 0,
    baseCost: { risitasium: 200, stickers: 100, sel: 0 },
    costFactor: 2,
    basePoints: 3,
    reqs: { 'laboratoire_recherche': 2, 'tech_energie': 1 },
    image: 'https://images.unsplash.com/photo-1574360778004-945d8b2d4957?q=80&w=500&auto=format&fit=crop',
  },
  {
    id: 'tech_ions',
    name: 'Canon à Shitpost',
    description: 'Bombardement ionique de masse.',
    level: 0,
    baseCost: { risitasium: 1000, stickers: 300, sel: 100 },
    costFactor: 2,
    basePoints: 10,
    reqs: { 'laboratoire_recherche': 4, 'tech_laser': 5, 'tech_energie': 4 },
    image: 'https://images.unsplash.com/photo-1518546305927-5a555bb7020d?q=80&w=500&auto=format&fit=crop',
  },
  {
    id: 'tech_hyperespace',
    name: 'Faille 410',
    description: 'Manipulation de l\'espace-temps pour disparaître.',
    level: 0,
    baseCost: { risitasium: 0, stickers: 4000, sel: 2000 },
    costFactor: 2,
    basePoints: 30,
    reqs: { 'laboratoire_recherche': 7, 'tech_energie': 5, 'tech_bouclier': 5 },
    image: 'https://images.unsplash.com/photo-1506318137071-a8bcbf6755dd?q=80&w=500&auto=format&fit=crop',
  },
  {
    id: 'tech_plasma',
    name: 'Technologie Plasma',
    description: 'L\'état ultime de la matière toxique.',
    level: 0,
    baseCost: { risitasium: 2000, stickers: 4000, sel: 1000 },
    costFactor: 2,
    basePoints: 20,
    reqs: { 'laboratoire_recherche': 4, 'tech_energie': 8, 'tech_laser': 10 },
    image: 'https://images.unsplash.com/photo-1533613220915-609f661a6fe1?q=80&w=500&auto=format&fit=crop',
  },
  {
    id: 'moteur_combustion',
    name: 'Moteur Diesel',
    description: 'Propulsion classique polluante.',
    level: 0,
    baseCost: { risitasium: 400, stickers: 0, sel: 600 },
    costFactor: 2,
    basePoints: 5,
    reqs: { 'laboratoire_recherche': 1, 'tech_energie': 1 },
    image: 'https://images.unsplash.com/photo-1580637250482-5c8e3100693a?q=80&w=500&auto=format&fit=crop',
  },
  {
    id: 'moteur_impulsion',
    name: 'Propulsion Hype',
    description: 'Moteur alimenté par la tendance.',
    level: 0,
    baseCost: { risitasium: 2000, stickers: 4000, sel: 600 },
    costFactor: 2,
    basePoints: 15,
    reqs: { 'laboratoire_recherche': 2, 'tech_energie': 1 },
    image: 'https://images.unsplash.com/photo-1542475510-99e53a1a387a?q=80&w=500&auto=format&fit=crop',
  },
  {
    id: 'moteur_hyperspace',
    name: 'Propulsion Spatio-Temporelle',
    description: 'Voyager plus vite que la modération.',
    level: 0,
    baseCost: { risitasium: 10000, stickers: 20000, sel: 6000 },
    costFactor: 2,
    basePoints: 50,
    reqs: { 'laboratoire_recherche': 7, 'tech_hyperespace': 3 },
    image: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?q=80&w=500&auto=format&fit=crop',
  },
  {
    id: 'espionnage',
    name: 'Algorithme de Stalking',
    description: 'Améliore la collecte d\'informations.',
    level: 0,
    baseCost: { risitasium: 200, stickers: 1000, sel: 200 },
    costFactor: 2,
    basePoints: 4,
    reqs: { 'laboratoire_recherche': 3 },
    image: 'https://images.unsplash.com/photo-1504639725590-34d0984388bd?q=80&w=500&auto=format&fit=crop',
  },
  {
    id: 'ordinateur',
    name: 'I.A. Célestin',
    description: 'Gère plus de flottes simultanément.',
    level: 0,
    baseCost: { risitasium: 0, stickers: 400, sel: 600 },
    costFactor: 2,
    basePoints: 6,
    reqs: { 'laboratoire_recherche': 1 },
    image: 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?q=80&w=500&auto=format&fit=crop',
  },
  {
    id: 'tech_armure',
    name: 'Blindage Anti-Ban',
    description: 'Renforce la structure des vaisseaux.',
    level: 0,
    baseCost: { risitasium: 1000, stickers: 0, sel: 0 },
    costFactor: 2,
    basePoints: 5,
    reqs: { 'laboratoire_recherche': 2 },
    image: 'https://images.unsplash.com/photo-1580894732444-8ecded7900cd?q=80&w=500&auto=format&fit=crop',
  },
  {
    id: 'tech_bouclier',
    name: 'Bouclier "Miroir Magique"',
    description: 'Renvoie les attaques à l\'envoyeur.',
    level: 0,
    baseCost: { risitasium: 200, stickers: 600, sel: 0 },
    costFactor: 2,
    basePoints: 5,
    reqs: { 'laboratoire_recherche': 6, 'tech_energie': 3 },
    image: 'https://images.unsplash.com/photo-1517480447814-2396e9877114?q=80&w=500&auto=format&fit=crop',
  },
];

export const SHIP_DB: Ship[] = [
  {
    id: 'sonde',
    name: 'Drone Mouchard',
    description: 'Petit drone rapide pour espionner les galaxies voisines.',
    count: 0,
    baseCost: { risitasium: 0, stickers: 1000, sel: 0 },
    costFactor: 1,
    basePoints: 1,
    stats: { attack: 0, defense: 0, hull: 100, capacity: 5 },
    reqs: { 'chantier_spatial': 1, 'moteur_combustion': 1, 'espionnage': 2 },
    image: 'https://images.unsplash.com/photo-1518364538800-6bae3c2db31e?q=80&w=500&auto=format&fit=crop',
  },
  {
    id: 'chasseur_leger',
    name: 'Kheyou de l\'Espace',
    description: 'Vaisseau de base. Rapide mais fragile.',
    count: 0,
    baseCost: { risitasium: 3000, stickers: 1000, sel: 0 },
    costFactor: 1,
    basePoints: 4,
    stats: { attack: 50, defense: 10, hull: 400, capacity: 50 },
    reqs: { 'chantier_spatial': 1, 'moteur_combustion': 1 },
    image: 'https://images.unsplash.com/photo-1581091226033-d5c48150dbaa?q=80&w=500&auto=format&fit=crop',
  },
  {
    id: 'chasseur_lourd',
    name: 'Kheyou de l\'Espace Lourd',
    description: 'Meilleure armure, parfait pour le raid.',
    count: 0,
    baseCost: { risitasium: 6000, stickers: 4000, sel: 0 },
    costFactor: 1,
    basePoints: 10,
    stats: { attack: 150, defense: 100, hull: 1000, capacity: 100 },
    reqs: { 'chantier_spatial': 3, 'moteur_impulsion': 2, 'tech_armure': 2 },
    image: 'https://images.unsplash.com/photo-1563089145-599997674d42?q=80&w=500&auto=format&fit=crop',
  },
  {
    id: 'croiseur',
    name: 'Modo-Croiseur',
    description: 'Vaisseau rapide capable de calmer les chasseurs.',
    count: 0,
    baseCost: { risitasium: 20000, stickers: 7000, sel: 2000 },
    costFactor: 1,
    basePoints: 29,
    stats: { attack: 400, defense: 100, hull: 2700, capacity: 800 },
    reqs: { 'chantier_spatial': 7, 'moteur_impulsion': 4, 'tech_ions': 2 },
    image: 'https://images.unsplash.com/photo-1550747545-c896b5f89304?q=80&w=500&auto=format&fit=crop',
  },
  {
    id: 'vaisseau_bataille',
    name: 'Cuirassonche',
    description: 'La puissance de feu principale de la flotte.',
    count: 0,
    baseCost: { risitasium: 45000, stickers: 15000, sel: 0 },
    costFactor: 1,
    basePoints: 60,
    stats: { attack: 1000, defense: 400, hull: 6000, capacity: 1500 },
    reqs: { 'chantier_spatial': 7, 'moteur_hyperspace': 4 },
    image: 'https://images.unsplash.com/photo-1534971727092-237cb71a17cb?q=80&w=500&auto=format&fit=crop',
  },
  {
    id: 'colonisateur',
    name: 'Créateur de French Dream',
    description: 'Permet de fonder une nouvelle colonie pavillonnaire.',
    count: 0,
    baseCost: { risitasium: 10000, stickers: 20000, sel: 10000 },
    costFactor: 1,
    basePoints: 40,
    stats: { attack: 50, defense: 100, hull: 3000, capacity: 7500 },
    reqs: { 'chantier_spatial': 4, 'moteur_impulsion': 3, 'astrophysique': 2 },
    image: 'https://images.unsplash.com/photo-1444703686981-a3abbc4d4fe3?q=80&w=500&auto=format&fit=crop',
  },
  {
    id: 'recycleur',
    name: 'Camion Poubelle Galactique',
    description: 'Récolte les débris après les batailles.',
    count: 0,
    baseCost: { risitasium: 10000, stickers: 6000, sel: 2000 },
    costFactor: 1,
    basePoints: 18,
    stats: { attack: 1, defense: 10, hull: 1600, capacity: 20000 },
    reqs: { 'chantier_spatial': 4, 'moteur_combustion': 6, 'tech_bouclier': 2 },
    image: 'https://images.unsplash.com/photo-1506452305024-9d3f02d1c9b5?q=80&w=500&auto=format&fit=crop',
  },
  {
    id: 'bombardier',
    name: 'Bombardier de la Chancla',
    description: 'Détruit les défenses planétaires.',
    count: 0,
    baseCost: { risitasium: 50000, stickers: 25000, sel: 15000 },
    costFactor: 1,
    basePoints: 90,
    stats: { attack: 1000, defense: 500, hull: 7500, capacity: 500 },
    reqs: { 'chantier_spatial': 8, 'moteur_impulsion': 6, 'tech_plasma': 5 },
    image: 'https://images.unsplash.com/photo-1560264280-88b68371db39?q=80&w=500&auto=format&fit=crop',
  },
  {
    id: 'destructeur',
    name: 'Destructeur de Pseudo',
    description: 'Le roi des batailles spatiales.',
    count: 0,
    baseCost: { risitasium: 60000, stickers: 50000, sel: 15000 },
    costFactor: 1,
    basePoints: 125,
    stats: { attack: 2000, defense: 2000, hull: 11000, capacity: 2000 },
    reqs: { 'chantier_spatial': 9, 'moteur_hyperspace': 6, 'tech_hyperespace': 5 },
    image: 'https://images.unsplash.com/photo-1533742493393-27715f573752?q=80&w=500&auto=format&fit=crop',
  },
  {
    id: 'etoile_noire',
    name: 'Approche du Goulag',
    description: 'Puissance destructrice capable d\'effacer des lunes.',
    count: 0,
    baseCost: { risitasium: 5000000, stickers: 4000000, sel: 1000000 },
    costFactor: 1,
    basePoints: 10000,
    stats: { attack: 200000, defense: 50000, hull: 900000, capacity: 1000000 },
    reqs: { 'chantier_spatial': 12, 'moteur_hyperspace': 7, 'tech_hyperespace': 6, 'graviton': 1 },
    image: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?q=80&w=500&auto=format&fit=crop',
  },
];
